fieldLayouts:
  f918d796-9987-435c-865e-4a8ec198d7ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d35fa4ed-3f7c-491d-ae45-48e0332a6ffd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 356765ad-7215-4292-a70a-f04d0f0d44a6 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 729ca87d-1bf7-4572-b23e-981a132a077a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ac771eb-c1c5-494d-8c21-ae3ac3bbb22f # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5465b584-986e-4aa1-80da-c97ad4130c7e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f97201cc-133c-45b1-aa56-28846662b2ff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 17cc42c1-6276-4fcd-8199-7b779f8cd93f # MRider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f03a650-3011-4b18-b1fb-8703dd650adb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7044ba8b-8802-4c51-87ae-126c8045f356 # Riders Intro Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10f08f8d-914c-4486-9fb0-f4d4e4ffcc5c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59d958b4-f306-49ce-9fcc-781fead2613c # Rider
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 766ac795-34b9-45af-95a1-d32e9a35f9e0
            userCondition: null
            warning: null
            width: 100
        name: Riders
        uid: eeddca47-1e69-4748-8710-0dcc637757bb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6c699954-a793-4faa-ac70-5bb90e3868fe # Featured Story
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48ea36b0-c8b8-43fd-a2b3-236fa06294c8
            userCondition: null
            warning: null
            width: 100
        name: 'Featured Stories'
        uid: a3b4053a-ab72-424b-928b-5ca408d58dde
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 8d6ce9b1-d995-4eed-a294-eb96480f7c6e # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
