columnSuffix: null
contentColumnType: string
fieldGroup: b8185e64-4790-4361-bb06-a18929c9116b # Home
handle: featuredStory
instructions: null
name: 'Featured Story'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Select a story'
  showSiteMenu: false
  source: null
  sources:
    - 'section:ebf40886-b893-4d2f-9a1d-f6249fa12446' # Stories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
