columnSuffix: null
contentColumnType: string
fieldGroup: a48a8c9a-1557-4a78-b154-fdf723b52e6a # Common
handle: navLinks
instructions: null
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
