fieldLayouts:
  e80a3fbf-7c89-41ee-a299-d94d893b5525:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a729da46-3ea4-4ca8-a1ba-7ba02c901ed1 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57d95567-1bef-4a2f-bcd1-d3f1841b4bd6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f55729d-90d5-446a-8a7c-574867c5436e
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
