defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  da3c6878-a68a-4c33-a256-2792f6fa5700: # Unit Ops Media
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
